themesDir: "../.."
# baseURL: "https://apps.nsercresnet.ca/story/monteregie/"
baseURL: "http://localhost:1313"
canonifyURLs: false
defaultContentLanguage : "en"
defaultContentLanguageInSubdir : true
languages:
  en:
    languageName: English
    weight: 1
  # fr:
  #   languageName: Français
  #   weight: 2