themesDir: "../.."
# baseURL: "https://apps.nsercresnet.ca/story/monteregie/"
# baseURL: "http://localhost:1313"
baseURL: "https://dev.xylemgeo.com/"
canonifyURLs: false
defaultContentLanguage : "en"
# defaultContentLanguageInSubdir : true
defaultContentLanguageInSubdir : false
languages:
  en:
    languageName: English
    weight: 1
  # fr:
  #   languageName: Français
  #   weight: 2
publishDir: docs